### ISSUE TITLE
老哥可以发一下nginx的配置文件吗

### ISSUE THREAD

**Issue by loongzcode** [raxcl/raxcl-blog#1]
老哥可以发一下nginx的配置文件吗

**Comment by Raxcl** [comment]
抱歉呢回复的可能有点晚了，但还是回复一下吧。
[https://blog.csdn.net/RAXCL/article/details/121276028](https://blog.csdn.net/RAXCL/article/details/121276028)，可以参考一下我的博客，里面有详细的部署教程，以及完整的nginx配置文件
